config/routes.rb
Taskapp::Application.routes.draw do
  resources :projects do
    member do
      get 'adduser'
    end
  end

  devise_for :users

  resources :documents

  resources :teammates

  resources :tasks do
    member do
      put 'mark_completed'
    end
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :duedate, :name,  :completed, :project_id
  validates :name, :presence => true
  validates :name, :uniqueness => {:value => true, :message => "only one task with same name"}
  validates :description, :length => {:maximum => 50}
  validates :project_id, :presence => true

  has_one :document
  belongs_to :project

  scope :due_soon, lambda { where(:duedate => (Date.today..Date.today.advance(:weeks => 1)))}
  scope :incomplete, where(:completed => false)
  scope :complete, where(:completed => true)



  def default_values
    self.completed = false
  end

  def getprojectname(projectid)
    if(projectid.nil?)
      pro = "No Associated Project"
    else
      pro =  Project.find(projectid).name
      end
  end






end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  before_filter :authenticate_user!


  def index

    @dues = current_user.getalltasks.due_soon.incomplete
    @incomp = current_user.getalltasks.incomplete
    @comp = current_user.getalltasks.complete

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => {:incomp => @incomp,
                                      :dues => @dues,
                                      :comp => @comp}}
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
        @email = current_user.email
        Notifications.new_task(@email, @task).deliver
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end
  # PUT /tasks/1/mark_completed
  def mark_completed
    @task = Task.find(params[:id])
    @task.update_column(:completed, true)
    respond_to do |format|
         format.html { redirect_to tasks_url }
    end
  end
  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_duesoon.erb
<h1>hihihihihi</h1>
<table class="table-bordered offset1">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Due Date</th>
  </tr>

  <% @dues.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.duedate.to_formatted_s(:long_ordinal) %></td>

      </tr>
  <% end %>
</table>

app/views/tasks/_form.html.erb
<%= render :partial => 'home/header' %>
<%= render :partial => 'home/help' %>

<%= form_for @task, :html => { :class => 'form-horizontal' } do |f| %>

    <% if @task.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

          <ul>
            <% @task.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :duedate, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :duedate, :class => 'date_select' %>
    </div>
  </div>
    <div class="control-group">
      <%= f.label :project, :class => 'control-label' %>
      <div class="controls">
        <%= f.collection_select(:project_id, current_user.projects , :id, :name) %>
      </div>
    </div>



  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tasks_path, :class => 'btn' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<%= render :partial => 'home/header' %>
<%= render :partial => 'home/help' %>
<div class="modal" style="display:none;">
</div>
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= link_to 'New', new_task_path, :class => "btn btn-primary"%>
<h3>Due Soon and Incomplete!</h3>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th> Project </th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:description) %></th>
    <th><%= model_class.human_attribute_name(:duedate) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th>Mark Complete?</th>
  </tr>
  </thead>
  <tbody>
  <% @dues.each do |task| %>
      <tr>
        <td><%= link_to task.id, task_path(task) %></td>
        <td><%= task.getprojectname(task.project_id) %></td>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.duedate.strftime("%b %d %Y") %></td>
        <td><%= task.created_at.strftime("%b %d %Y") %></td>
        <td>
          <%=  link_to "Completed!", mark_completed_task_path(task.id), :method => :put, :class => 'btn btn-success' %>
        </td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_task_path(task), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      task_path(task),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>

      </tr>
  <% end %>
  </tbody>
</table>

<h3>All Incomplete Tasks</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th> Project </th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:duedate) %></th>

      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th>Mark Complete?</th>
    </tr>
  </thead>
  <tbody>
    <% @incomp.each do |task| %>
      <tr>
        <td><%= link_to task.id, task_path(task) %></td>
        <td><%= task.getprojectname(task.project_id) %></td>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.duedate.strftime("%b %d %Y") %></td>
        <td><%= task.created_at.strftime("%b %d %Y") %></td>
        <td><%=  link_to "Completed!", mark_completed_task_path(task.id), :method => :put, :class => 'btn btn-success' %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_task_path(task), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      task_path(task),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<h3>Complete Tasks</h3>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th> Project </th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:description) %></th>
    <th><%= model_class.human_attribute_name(:duedate) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
  </tr>
  </thead>
  <tbody>
  <% @comp.each do |task| %>
      <tr>
        <td><%= link_to task.id, task_path(task) %></td>
        <td><%= task.getprojectname(task.project_id) %></td>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.duedate.strftime("%b %d %Y") %></td>

        <td><%= task.created_at.strftime("%b %d %Y")%></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_task_path(task), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      task_path(task),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<%= render :partial => 'home/header' %>
<%= render :partial => 'home/help' %>
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @task.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @task.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:duedate) %>:</strong></dt>
  <dd><%= @task.duedate %></dd>

</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              tasks_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_task_path(@task), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              task_path(@task),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>