config/routes.rb
Taskapp::Application.routes.draw do
  resources :projects do
    member do
      get 'adduser'
    end
  end

  devise_for :users

  resources :documents

  resources :teammates

  resources :tasks do
    member do
      put 'mark_completed'
    end
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :datemodified, :name, :docurl, :project_id
  validates :name, :presence => true
  validates :docurl, :presence => true
  belongs_to :project

  def getprojectname(projectid)
    if(@projectid.nil?)
      pro = "No Associated Project"
    else
      pro =  Project.find(projectid).name
    end
  end

  def checkurl
    unless self.docurl[/^http:\/\//] || self.docurl[/^https:\/\//]
      self.docurl = 'http://' + self.docurl
    end
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  # GET /documents
  # GET /documents.json
  before_filter :authenticate_user!
  def index
    @documents = Document.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/new
  # GET /documents/new.json
  def new
    @document = Document.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(params[:document])
    @document.checkurl
    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /documents/1
  # PUT /documents/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= render :partial => 'home/header' %>
<%= render :partial => 'home/help' %>
<%= form_for @document, :html => { :class => 'form-horizontal' } do |f| %>
    <% if @document.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

          <ul>
            <% @document.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

    <div class="control-group">
      <%= f.label 'Document Link', :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :docurl, :class => 'text_field' %>
      </div>
    </div>


    <div class="control-group">
      <%= f.label :project, :class => 'control-label' %>
      <div class="controls">
        <%= f.collection_select(:project_id, current_user.projects , :id, :name) %>
      </div>
    </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                documents_path, :class => 'btn' %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/documents/index.html.erb
<%= render :partial => 'home/header' %>
<%= render :partial => 'home/help' %>

<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th> Link to Document</th>
      <th> Associated Project</th>
      <th> Date Added</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= link_to document.id, document_path(document) %></td>
        <td><%= link_to document.name, document.docurl %></td>
        <td><%= document.getprojectname(document.project_id) %></td>
        <td><%= document.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_document_path(document), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      document_path(document),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_document_path,
            :class => 'btn btn-primary' %>

app/views/documents/new.html.erb
<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/documents/show.html.erb
<%= render :partial => 'home/header' %>
<%= render :partial => 'home/help' %>

<%- model_class = Document -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @document.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:docurl) %>:</strong></dt>
  <dd><%= @document.docurl %></dd>
  <dt><strong><%= model_class.human_attribute_name(:datemodified) %>:</strong></dt>
  <dd><%= @document.datemodified %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              documents_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_document_path(@document), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              document_path(@document),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>