config/routes.rb
Taskapp::Application.routes.draw do
  resources :projects do
    member do
      get 'adduser'
    end
  end

  devise_for :users

  resources :documents

  resources :teammates

  resources :tasks do
    member do
      put 'mark_completed'
    end
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name,  :teammate_id, :user_ids
  validates :name, :presence => true
  has_and_belongs_to_many :users
  has_many :tasks
  has_many :documents

 def addCreatorToProject(userid)
   u = User.find(userid)
   self.users << u
 end

  def getnames
    @stringtoret = ""
    @userstosend = User.where(:id => self.user_ids)
    @userstosend.each do |user|
      if @stringtoret == ""
        @stringtoret = user.name
      else
       @stringtoret = @stringtoret + ", " + user.name
      end
    end
    return @stringtoret
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/adduser
  def adduser
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html #adduser.html.erb
      format.json {render json: @project}
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @project.addCreatorToProject(current_user.id)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end

    current_user.sendnotification(@project.id)
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= render :partial => 'home/header' %>
<%= render :partial => 'home/help' %>
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/adduser.html.erb
<%= render :partial => 'home/header' %>
<%= render :partial => 'home/help' %>
<%- model_class = Project -%>
<div class="page-header">
  <h1>Add New Teammate to Project</h1>
</div>
<%= form_for(@project) do |f| %>
<% for user in User.find(:all) %>
<div>
  <label>
  <%= check_box_tag "project[user_ids][]", user.id,
  @project.users.include?(user) %>
  <%=  user.name%>
  <%=  user.email %>
  </label>
</div>
<% end %>

    <div class="actions">
      <%= f.submit %>

    </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<%= render :partial => 'home/header' %>
<%= render :partial => 'home/help' %>

<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th>Teammates</th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td>
          <table class="table table-striped">
            <thead>
            <tr>
              <th>Name</th>
              <th>Email</th>
            </tr>
            </thead>
            <tbody>
            <% for user in User.all(:include => :projects,:conditions => ["projects.id = ?", project.id]) %>
                <tr>
                  <td><%= user.name %></td>
                  <td><%= user.email %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </td>
        <td>
          <%= link_to 'Add Teammate', adduser_project_path(project), :class => 'btn btn-mini'%>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(project), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>

  <% end %>
  </tr>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<%= render :partial => 'home/header' %>
<%= render :partial => 'home/help' %>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>