config/routes.rb
Taskapp::Application.routes.draw do
  resources :projects do
    member do
      get 'adduser'
    end
  end

  devise_for :users

  resources :documents

  resources :teammates

  resources :tasks do
    member do
      put 'mark_completed'
    end
  end

  get "home/index"

  root :to => 'home#index'

end

app/models/teammate.rb
class Teammate < ActiveRecord::Base
  attr_accessible :email, :name
  validates :name, :presence => true
  validates :name, :uniqueness => {:value => true, :message => "Teammate already exists"}
  validates :email, :format => { :with => /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i}
end

app/controllers/teammates_controller.rb
class TeammatesController < ApplicationController
  # GET /teammates
  # GET /teammates.json
  before_filter :authenticate_user!
  def index
    @teammates = Teammate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teammates }
    end
  end

  # GET /teammates/1
  # GET /teammates/1.json
  def show
    @teammate = Teammate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @teammate }
    end
  end

  # GET /teammates/new
  # GET /teammates/new.json
  def new
    @teammate = Teammate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @teammate }
    end
  end

  # GET /teammates/1/edit
  def edit
    @teammate = Teammate.find(params[:id])
  end

  # POST /teammates
  # POST /teammates.json
  def create
    @teammate = Teammate.new(params[:teammate])

    respond_to do |format|
      if @teammate.save
        format.html { redirect_to @teammate, notice: 'Teammate was successfully created.' }
        format.json { render json: @teammate, status: :created, location: @teammate }
      else
        format.html { render action: "new" }
        format.json { render json: @teammate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teammates/1
  # PUT /teammates/1.json
  def update
    @teammate = Teammate.find(params[:id])

    respond_to do |format|
      if @teammate.update_attributes(params[:teammate])
        format.html { redirect_to @teammate, notice: 'Teammate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @teammate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teammates/1
  # DELETE /teammates/1.json
  def destroy
    @teammate = Teammate.find(params[:id])
    @teammate.destroy

    respond_to do |format|
      format.html { redirect_to teammates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/teammates_helper.rb
module TeammatesHelper
end

app/views/teammates/_form.html.erb
<header>
  <div class="container">
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">GetItDone</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="/"><i class="icon-home icon-white"></i> Home</a></li>
              <li><a href= "/teammates">Teammates</a></li>
              <li><a href="/tasks">Tasks</a></li>
              <li><a href="/documents">Documents</a></li>

            </ul>
            <div class="navbar-text pull-right">
              <% if user_signed_in? %>
                  Logged in as <strong><%= current_user.email %></strong>.
                  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
                  <%= link_to "Register", new_user_registration_path, :class => 'navbar-link'  %> |
                  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
              <% end %>
            </div>

          </div><!-- /.nav-collapse -->

        </div><!-- /.container -->


      </div>
    </div><!-- /.navbar-inner -->
  </div><!-- /.navbar -->
  </div>
</header>

<%= form_for @teammate, :html => { :class => 'form-horizontal' } do |f| %>

    <% if @teammate.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@teammate.errors.count, "error") %> prohibited this teammate from being saved:</h2>

          <ul>
            <% @teammate.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                teammates_path, :class => 'btn' %>
  </div>
<% end %>

app/views/teammates/edit.html.erb
<%- model_class = Teammate -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/teammates/index.html.erb
<header>
  <div class="container">
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">GetItDone</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="/"><i class="icon-home icon-white"></i> Home</a></li>
              <li><a href= "/teammates">Teammates</a></li>
              <li><a href="/tasks">Tasks</a></li>
              <li><a href="/documents">Documents</a></li>

            </ul>
            <div class="navbar-text pull-right">
              <% if user_signed_in? %>
                  Logged in as <strong><%= current_user.email %></strong>.
                  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
                  <%= link_to "Register", new_user_registration_path, :class => 'navbar-link'  %> |
                  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
              <% end %>
            </div>

          </div><!-- /.nav-collapse -->

        </div><!-- /.container -->


      </div>
    </div><!-- /.navbar-inner -->
  </div><!-- /.navbar -->
  </div>
</header>

<%- model_class = Teammate -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @teammates.each do |teammate| %>
      <tr>
        <td><%= link_to teammate.id, teammate_path(teammate) %></td>
        <td><%= teammate.name %></td>
        <td><%= teammate.email %></td>
        <td><%=l teammate.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_teammate_path(teammate), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      teammate_path(teammate),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_teammate_path,
            :class => 'btn btn-primary' %>

app/views/teammates/new.html.erb
<%- model_class = Teammate -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/teammates/show.html.erb
<header>
  <div class="container">
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">GetItDone</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="/"><i class="icon-home icon-white"></i> Home</a></li>
              <li><a href= "/teammates">Teammates</a></li>
              <li><a href="/tasks">Tasks</a></li>
              <li><a href="/documents">Documents</a></li>

            </ul>
            <div class="navbar-text pull-right">
              <% if user_signed_in? %>
                  Logged in as <strong><%= current_user.email %></strong>.
                  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
              <% else %>
                  <%= link_to "Register", new_user_registration_path, :class => 'navbar-link'  %> |
                  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
              <% end %>
            </div>

          </div><!-- /.nav-collapse -->

        </div><!-- /.container -->


      </div>
    </div><!-- /.navbar-inner -->
  </div><!-- /.navbar -->
  </div>
</header>

<%- model_class = Teammate -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @teammate.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @teammate.email %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              teammates_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_teammate_path(@teammate), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              teammate_path(@teammate),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>